### ISSUE TITLE
Fails on systems where python2 is the default

### ISSUE THREAD

**Issue by Zer0t3ch** [bluepeppers/archey3#29]
Suggest changing to first line of `archey3` to:

    #!/usr/bin/env python2

**Comment by bluepeppers** [comment]
Archey 3 is a python3 only program, sorry

**Comment by mariusmagureanu** [comment]
If you've got both **python2** and **python3** then it's rather easy to have it fixed:

`#!/usr/bin/python3` 

instead of the original line:

`#!/usr/bin/python`
