### ISSUE TITLE
archey3 next steps

### ISSUE THREAD

**Issue by HLFH** [bluepeppers/archey3#52]
Hi @lclarkmichalek,

Supporters from the fork `archey4` want to merge my [`archey3-git` AUR package](https://aur.archlinux.org/packages/archey3-git) with `archey4` and take the votes and comments related to your package.

There was a request of the `archey3-git` package for deletion. It does have 171 votes that show how your program is appreciated.

What is your take on this? Do you:

 - want to archive this `archey3` repo which may have as a consequence the deletion of `archey3-git` AUR package;
 - have any intent to continue developing `archey3` at some point in time;
 - support the fork `archey4` in some way.

**Comment by lclarkmichalek** [comment]
Ship it! My only sadness is that we're increasing the suffix linearly, and
haven't gone for archey5 or some other nice prime.

I will archive this repo - my archeying days are over, I am sad to report.

**Comment by HLFH** [comment]
Ok thank you.

I will close this issue as I understand you may soon archive this repo and you confirmed you no longer continue the development.
